name: Create Pull Request

on:
  push:
    branches:
      - junaid

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: 'Merge junaid into main'
          body: 'This pull request was automatically created.'
